import { createRoot } from 'react-dom/client';
import './styles/index.css';

const nativeFetch = window.fetch.bind(window);
const MAX_UPLOAD_BYTES = 100 * 1024 * 1024;
const uploadControllers = new Map<string, AbortController>();
const uploadPayloads = new Map<string, Record<string, unknown>>();

type UploadEvent = { id: string; fileName?: string; projectName?: string; status?: string; progress?: number; error?: string };
function emit(name: string, detail: UploadEvent) { window.dispatchEvent(new CustomEvent(name, { detail })); }
function decodedBase64Bytes(base64: string) { const padding = base64.endsWith('==') ? 2 : base64.endsWith('=') ? 1 : 0; return Math.floor(base64.length * 3 / 4) - padding; }
function dataUrlToBlob(dataUrl: string) { const match = dataUrl.match(/^data:([^;,]+);base64,(.+)$/s); if (!match) throw new Error('Invalid optimized image data'); const bytes = Uint8Array.from(atob(match[2]), (char) => char.charCodeAt(0)); return new Blob([bytes], { type: match[1].toLowerCase() }); }
async function imageDimensions(blob: Blob) { try { const bitmap = await createImageBitmap(blob); const result = { width: bitmap.width || null, height: bitmap.height || null }; bitmap.close(); return result; } catch { return { width: null, height: null }; } }
async function verifyObject(uploadUrl: string, storageKey: string, expectedType: string, expectedSize: number, controller: AbortController) { const url = new URL(uploadUrl); url.searchParams.set('key', storageKey); const response = await nativeFetch(url.toString(), { cache: 'no-store', signal: controller.signal }); if (!response.ok) throw new Error(`Neon Object Storage verification failed (${response.status})`); const contentType = response.headers.get('content-type') || ''; const contentLength = Number(response.headers.get('content-length') || expectedSize); if (!contentType.startsWith(expectedType.split(';')[0])) throw new Error(`Stored media type mismatch: ${contentType}`); if (contentLength !== expectedSize) throw new Error(`Stored media size mismatch: ${contentLength}`); }
async function verifyPublicMedia(mediaId: string, controller: AbortController) { const response = await nativeFetch(`/api/portfolio?media=${encodeURIComponent(mediaId)}&verify=${Date.now()}`, { cache: 'no-store', signal: controller.signal }); if (!response.ok) throw new Error(`Public media delivery verification failed (${response.status})`); const contentType = response.headers.get('content-type') || ''; if (!contentType.startsWith('image/')) throw new Error(`Public media returned invalid content type: ${contentType}`); }
function xhrUpload(url: string, token: string, blob: Blob, controller: AbortController, uploadKey: string) { return new Promise<void>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open('POST', url, true); xhr.setRequestHeader('x-bluehaven-token', token); xhr.setRequestHeader('content-type', blob.type || 'application/octet-stream'); xhr.upload.onprogress = (event) => { if (event.lengthComputable) emit('bluehaven:upload-progress', { id: uploadKey, progress: Math.round((event.loaded / event.total) * 100) }); }; xhr.onerror = () => reject(new Error('Network error while uploading to Neon Object Storage')); xhr.onabort = () => reject(new DOMException('Upload cancelled', 'AbortError')); xhr.onload = () => { let data: any = {}; try { data = JSON.parse(xhr.responseText || '{}'); } catch {} if (xhr.status < 200 || xhr.status >= 300 || !data?.ok) return reject(new Error(data?.error || `Neon storage upload failed (${xhr.status})`)); resolve(); }; controller.signal.addEventListener('abort', () => xhr.abort(), { once: true }); xhr.send(blob); }); }

async function bridgeUpload(payload: Record<string, unknown>, uploadKey: string, controller: AbortController) {
  const dataUrl = String(payload.data_url || ''); const originalSize = decodedBase64Bytes(dataUrl.split(',')[1] || ''); if (originalSize > MAX_UPLOAD_BYTES) throw new Error('Image must be 100MB or smaller');
  const optimizedBlob = dataUrlToBlob(dataUrl); const projectId = String(payload.project_id || ''); const fileName = String(payload.file_name || 'upload'); const mimeType = String(optimizedBlob.type || payload.mime_type || ''); if (!projectId) throw new Error('Missing project id');
  const mediaId = String(payload.media_id || crypto.randomUUID()); const dimensions = await imageDimensions(optimizedBlob);
  const prepResponse = await nativeFetch('/api/portfolio', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'prepare_upload', project_id: projectId, media_id: mediaId, file_name: fileName, mime_type: mimeType, alt_text: String(payload.alt_text || 'BlueHaven Studio work') }), signal: controller.signal });
  const prep = await prepResponse.json().catch(() => ({})); if (!prepResponse.ok || !prep?.ok) throw new Error(prep?.error || 'Could not prepare Neon Object Storage upload');
  emit('bluehaven:upload-stage', { id: uploadKey, status: 'uploading', progress: 0 }); await xhrUpload(String(prep.upload_url), String(prep.token), optimizedBlob, controller, uploadKey);
  emit('bluehaven:upload-stage', { id: uploadKey, status: 'verifying', progress: 100 }); await verifyObject(String(prep.upload_url), String(prep.storage_key), mimeType, optimizedBlob.size, controller);
  const registerResponse = await nativeFetch('/api/portfolio', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'register_upload', project_id: projectId, media_id: mediaId, file_name: fileName, mime_type: mimeType, alt_text: String(payload.alt_text || 'BlueHaven Studio work'), storage_key: prep.storage_key, file_size: optimizedBlob.size, width: dimensions.width, height: dimensions.height }), signal: controller.signal });
  const registered = await registerResponse.json().catch(() => ({})); if (!registerResponse.ok || !registered?.ok) throw new Error(registered?.error || 'Image uploaded but could not be registered in Neon');
  await verifyPublicMedia(mediaId, controller); emit('bluehaven:upload-stage', { id: uploadKey, status: 'published', progress: 100 });
  return { id: mediaId, url: registered.url || prep.url, optimized: true, verified: true };
}

async function bridgeReplace(payload: Record<string, unknown>, uploadKey: string, controller: AbortController) {
  const optimizedBlob = dataUrlToBlob(String(payload.data_url || '')); const mediaId = String(payload.id || ''); const fileName = String(payload.file_name || 'optimized.webp'); const mimeType = String(optimizedBlob.type || payload.mime_type || ''); const dimensions = await imageDimensions(optimizedBlob);
  const prepResponse = await nativeFetch('/api/portfolio', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'prepare_replace', id: mediaId, file_name: fileName, mime_type: mimeType }), signal: controller.signal }); const prep = await prepResponse.json().catch(() => ({}));
  if (!prepResponse.ok || !prep?.ok) throw new Error(prep?.error || 'Could not prepare Neon replacement');
  await xhrUpload(String(prep.upload_url), String(prep.token), optimizedBlob, controller, uploadKey); emit('bluehaven:upload-stage', { id: uploadKey, status: 'verifying', progress: 100 }); await verifyObject(String(prep.upload_url), String(prep.storage_key), mimeType, optimizedBlob.size, controller);
  const completeResponse = await nativeFetch('/api/portfolio', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'complete_replace', id: mediaId, storage_key: prep.storage_key, mime_type: mimeType, file_name: fileName, file_size: optimizedBlob.size, width: dimensions.width, height: dimensions.height }), signal: controller.signal }); const result = await completeResponse.json().catch(() => ({}));
  if (!completeResponse.ok || !result?.ok) throw new Error(result?.error || 'Could not save optimized image'); await verifyPublicMedia(mediaId, controller); emit('bluehaven:upload-stage', { id: uploadKey, status: 'published', progress: 100 }); return { ok: true, id: mediaId, url: result.url || prep.url, changed: true, optimized: true, verified: true };
}

async function waitForRegisteredMedia(mediaId: string, projectId: string) { for (let attempt = 0; attempt < 10; attempt += 1) { const response = await nativeFetch(`/api/portfolio?media_check=${encodeURIComponent(mediaId)}&project=${encodeURIComponent(projectId)}&t=${Date.now()}`, { cache: 'no-store' }); if (response.ok) { const data = await response.json().catch(() => null); const registered = Array.isArray(data?.media) && data.media.some((media: { id?: string; project_id?: string }) => media.id === mediaId && media.project_id === projectId); if (registered) return data; } if (attempt < 9) await new Promise(resolve => setTimeout(resolve, 500)); } throw new Error('Image uploaded, but the portfolio database has not confirmed it yet. Please retry in a moment.'); }
const uploadRetry = async (uploadKey: string) => { const payload = uploadPayloads.get(uploadKey); if (!payload) throw new Error('Upload data is no longer available. Please select the file again.'); const controller = new AbortController(); uploadControllers.set(uploadKey, controller); try { const result = payload.action === 'optimize_existing' ? await bridgeReplace(payload, uploadKey, controller) : await bridgeUpload(payload, uploadKey, controller); if (payload.action !== 'optimize_existing') await waitForRegisteredMedia(String(result.id), String(payload.project_id)); emit('bluehaven:upload-complete', { id: uploadKey, progress: 100 }); } finally { uploadControllers.delete(uploadKey); } };
type BlueHavenWindow = Window & { __bluehavenRetryUpload?: typeof uploadRetry; __bluehavenCancelUpload?: (id: string) => void };
(window as BlueHavenWindow).__bluehavenRetryUpload = uploadRetry; (window as BlueHavenWindow).__bluehavenCancelUpload = (id) => uploadControllers.get(id)?.abort();
window.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => { const url = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url; if (url.endsWith('/api/portfolio') && init?.method === 'POST' && typeof init.body === 'string') { try { const payload = JSON.parse(init.body); if ((payload?.action === 'upload' || payload?.action === 'optimize_existing') && typeof payload.data_url === 'string') { const uploadKey = String(payload.upload_key || crypto.randomUUID()); uploadPayloads.set(uploadKey, { ...payload, upload_key: uploadKey }); emit('bluehaven:upload-start', { id: uploadKey, fileName: String(payload.file_name || 'upload'), projectName: String(payload.alt_text || 'BlueHaven Studio work'), status: 'optimizing', progress: 0 }); const controller = new AbortController(); uploadControllers.set(uploadKey, controller); if (init.signal) init.signal.addEventListener('abort', () => controller.abort(), { once: true }); try { const result = payload.action === 'optimize_existing' ? await bridgeReplace(payload, uploadKey, controller) : await bridgeUpload(payload, uploadKey, controller); if (payload.action !== 'optimize_existing') await waitForRegisteredMedia(String(result.id), String(payload.project_id)); emit('bluehaven:upload-complete', { id: uploadKey, progress: 100 }); return new Response(JSON.stringify(result), { status: 200, headers: { 'content-type': 'application/json' } }); } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') { emit('bluehaven:upload-cancelled', { id: uploadKey }); return new Response(JSON.stringify({ error: 'Upload cancelled' }), { status: 499, headers: { 'content-type': 'application/json' } }); } const message = error instanceof Error ? error.message : 'Upload failed'; emit('bluehaven:upload-failed', { id: uploadKey, error: message }); console.error('BlueHaven Neon upload bridge error:', error); return new Response(JSON.stringify({ error: message }), { status: 400, headers: { 'content-type': 'application/json' } }); } finally { uploadControllers.delete(uploadKey); } } } catch (error) { console.error('BlueHaven upload bridge error:', error); return new Response(JSON.stringify({ error: error instanceof Error ? error.message : 'Upload failed' }), { status: 400, headers: { 'content-type': 'application/json' } }); } } return nativeFetch(input, init); };
Promise.all([import('./app/Admin'), import('./app/NeonSyncButton'), import('./app/UploadActivity')]).then(([{ default: Admin }, { default: NeonSyncButton }, { default: UploadActivity }]) => { createRoot(document.getElementById('admin-root')!).render(<><Admin /><NeonSyncButton /><UploadActivity /></>); });
