import { neon } from '@neondatabase/serverless';
import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
const scrypt=promisify(scryptCallback), COOKIE='bluehaven_writer_session';
const db=()=>{if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');return neon(process.env.DATABASE_URL)};
const body=(r:any)=>typeof r.body==='string'?JSON.parse(r.body||'{}'):(r.body||{});
const json=(r:any,d:any,s=200,h:any={})=>{r.status(s).setHeader('content-type','application/json').setHeader('cache-control','no-store');Object.entries(h).forEach(([k,v])=>r.setHeader(k,String(v)));return r.json(d)};
const cookie=(r:any)=>String(r.headers?.cookie||'').split(';').map((x:string)=>x.trim()).find((x:string)=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1)||'';
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
async function ensure(q:any){await q.query('CREATE TABLE IF NOT EXISTS bluehaven_authors(id UUID PRIMARY KEY,display_name VARCHAR(120) NOT NULL,username VARCHAR(40) UNIQUE NOT NULL,email VARCHAR(254) UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())');await q.query('CREATE TABLE IF NOT EXISTS bluehaven_writer_sessions(id UUID PRIMARY KEY,author_id UUID NOT NULL REFERENCES bluehaven_authors(id) ON DELETE CASCADE,token_hash CHAR(64) UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())')}
async function makeHash(p:string){const salt=randomBytes(16),h=await scrypt(p,salt,64,{N:32768,r:8,p:3}) as Buffer;return salt.toString('base64url')+'.'+h.toString('base64url')}
async function checkHash(p:string,v:string){const a=v.split('.'),expected=Buffer.from(a[1]||'','base64url');if(!a[0]||!expected.length)return false;const actual=await scrypt(p,Buffer.from(a[0],'base64url'),expected.length,{N:32768,r:8,p:3}) as Buffer;return timingSafeEqual(actual,expected)}
async function me(q:any,r:any){const t=cookie(r);if(!t)return null;const x=await q.query('SELECT a.id,a.display_name,a.username,a.email FROM bluehaven_writer_sessions s JOIN bluehaven_authors a ON a.id=s.author_id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1',[hash(t)]);return x.rows[0]||null}
export default async function handler(req:any,res:any){try{const q=db();await ensure(q);if(req.method==='GET')return json(res,{authenticated:Boolean(await me(q,req)),author:await me(q,req)});if(req.method!=='POST')return json(res,{error:'Method not allowed'},405);const d=body(req),a=String(d.action||'');
if(a==='register'){const name=String(d.displayName||'').trim().slice(0,120),username=String(d.username||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,40),email=String(d.email||'').trim().toLowerCase().slice(0,254),password=String(d.password||'');if(name.length<2||username.length<3||!/^\S+@\S+\.\S+$/.test(email)||password.length<12||password.length>128)return json(res,{error:'Use a name, valid email, username (3+ characters) and password (12–128 characters).'},400);const e=await q.query('SELECT id FROM bluehaven_authors WHERE email=$1 OR username=$2 LIMIT 1',[email,username]);if(e.rows[0])return json(res,{error:'That email or username is already in use.'},409);const id=randomUUID();await q.query('INSERT INTO bluehaven_authors(id,display_name,username,email,password_hash) VALUES($1,$2,$3,$4,$5)',[id,name,username,email,await makeHash(password)]);const t=randomBytes(32).toString('base64url');await q.query('INSERT INTO bluehaven_writer_sessions(id,author_id,token_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL \\'30 days\\')',[randomUUID(),id,hash(t)]);return json(res,{ok:true,author:{id,display_name:name,username,email}},200,{'set-cookie':COOKIE+'='+t+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000'})}
if(a==='login'){const identity=String(d.identity||'').trim().toLowerCase(),password=String(d.password||'');const x=await q.query('SELECT id,display_name,username,email,password_hash FROM bluehaven_authors WHERE email=$1 OR username=$1 LIMIT 1',[identity]);if(!x.rows[0]||!(await checkHash(password,x.rows[0].password_hash)))return json(res,{error:'Invalid email/username or password.'},401);const t=randomBytes(32).toString('base64url');await q.query('DELETE FROM bluehaven_writer_sessions WHERE author_id=$1',[x.rows[0].id]);await q.query('INSERT INTO bluehaven_writer_sessions(id,author_id,token_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL \\'30 days\\')',[randomUUID(),x.rows[0].id,hash(t)]);const author={id:x.rows[0].id,display_name:x.rows[0].display_name,username:x.rows[0].username,email:x.rows[0].email};return json(res,{ok:true,author},200,{'set-cookie':COOKIE+'='+t+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000'})}
if(a==='logout'){const t=cookie(req);if(t)await q.query('DELETE FROM bluehaven_writer_sessions WHERE token_hash=$1',[hash(t)]);return json(res,{ok:true},200,{'set-cookie':COOKIE+'=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
return json(res,{error:'Unknown action'},400)}catch(e){console.error('blog auth',e);return json(res,{error:e instanceof Error?e.message:'Authentication service error'},500)}}