import { neon } from '@neondatabase/serverless';
import { createHash, randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { isAuthenticated as isAdmin } from './_auth.js';
const scrypt=promisify(scryptCallback),COOKIE='bluehaven_writer_session';
const db=()=>{if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');return neon(process.env.DATABASE_URL)};
const body=(r:any)=>typeof r.body==='string'?JSON.parse(r.body||'{}'):(r.body||{}),send=(r:any,d:any,s=200,h:any={})=>{r.status(s).setHeader('content-type','application/json').setHeader('cache-control','no-store');Object.entries(h).forEach(([k,v])=>r.setHeader(k,String(v)));return r.json(d)};
const cookie=(r:any)=>String(r.headers?.cookie||'').split(';').map((x:string)=>x.trim()).find((x:string)=>x.startsWith(COOKIE+'='))?.slice(COOKIE.length+1)||'',hash=(v:string)=>createHash('sha256').update(v).digest('hex');
async function ensure(q:any){await q.query('CREATE TABLE IF NOT EXISTS bluehaven_authors(id UUID PRIMARY KEY,display_name VARCHAR(120) NOT NULL,username VARCHAR(40) UNIQUE NOT NULL,email VARCHAR(254) UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())');await q.query('CREATE TABLE IF NOT EXISTS bluehaven_writer_sessions(id UUID PRIMARY KEY,author_id UUID NOT NULL REFERENCES bluehaven_authors(id) ON DELETE CASCADE,token_hash CHAR(64) UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())');await q.query('CREATE TABLE IF NOT EXISTS bluehaven_blog_posts(id UUID PRIMARY KEY,author_id UUID NOT NULL REFERENCES bluehaven_authors(id) ON DELETE CASCADE,title VARCHAR(180) NOT NULL,slug VARCHAR(220) UNIQUE NOT NULL,excerpt VARCHAR(500) NOT NULL DEFAULT \\'\\',content TEXT NOT NULL DEFAULT \\'\\',category VARCHAR(80) NOT NULL DEFAULT \\'Community\\',cover_data BYTEA,cover_mime VARCHAR(80),status VARCHAR(20) NOT NULL DEFAULT \\'draft\\',published_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())');await q.query('CREATE INDEX IF NOT EXISTS bluehaven_blog_public_idx ON bluehaven_blog_posts(status,published_at DESC,created_at DESC)')}
async function me(q:any,r:any){const t=cookie(r);if(!t)return null;const x=await q.query('SELECT a.id,a.display_name,a.username,a.email FROM bluehaven_writer_sessions s JOIN bluehaven_authors a ON a.id=s.author_id WHERE s.token_hash=$1 AND s.expires_at>NOW() LIMIT 1',[hash(t)]);return x.rows[0]||null}
async function makeHash(p:string){const salt=randomBytes(16),h=await scrypt(p,salt,64,{N:32768,r:8,p:3}) as Buffer;return salt.toString('base64url')+'.'+h.toString('base64url')}
async function checkHash(p:string,v:string){const a=v.split('.'),expected=Buffer.from(a[1]||'','base64url');if(!a[0]||!expected.length)return false;const actual=await scrypt(p,Buffer.from(a[0],'base64url'),expected.length,{N:32768,r:8,p:3}) as Buffer;return timingSafeEqual(actual,expected)}
const makeSlug=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,220)||randomBytes(5).toString('hex');
function cover(v:any){const m=String(v||'').match(/^data:([^;]+);base64,(.+)$/s);if(!m)return null;const b=Buffer.from(m[2],'base64');if(b.length>12*1024*1024)throw new Error('Cover image is larger than 12MB');if(!['image/jpeg','image/png','image/webp'].includes(m[1]))throw new Error('Cover image must be JPG, PNG or WebP');return {mime:m[1],bytes:b}}
const shape=(p:any)=>{const x={...p,author_name:p.display_name,author_username:p.username,cover_url:p.cover_data?'/api/blog?media='+p.id:null};delete x.cover_data;delete x.password_hash;return x};
export default async function handler(req:any,res:any){try{const q=db();await ensure(q);const params=new URL(req.url||'/','https://bluehaven.local').searchParams;
if(req.method==='GET'&&params.get('media')){const x=await q.query('SELECT cover_data,cover_mime FROM bluehaven_blog_posts WHERE id=$1 LIMIT 1',[params.get('media')]);if(!x.rows[0]?.cover_data)return res.status(404).end('Not found');const b=x.rows[0].cover_data instanceof Uint8Array?x.rows[0].cover_data:Buffer.from(x.rows[0].cover_data,'base64');return res.status(200).setHeader('content-type',x.rows[0].cover_mime||'image/jpeg').setHeader('cache-control','public,max-age=31536000,immutable').end(b)}
if(req.method==='GET'){const a=await me(q,req),admin=isAdmin(req),wanted=params.get('slug');if(params.get('auth')==='1')return send(res,{authenticated:Boolean(a),author:a});if(wanted){const x=await q.query('SELECT p.*,a.display_name,a.username FROM bluehaven_blog_posts p JOIN bluehaven_authors a ON a.id=p.author_id WHERE p.slug=$1 AND (p.status=\\'published\\' OR $2 OR p.author_id=$3) LIMIT 1',[wanted,admin,a?.id||null]);if(!x.rows[0])return send(res,{error:'Post not found'},404);return send(res,{post:shape(x.rows[0])})}if(admin){const x=await q.query('SELECT p.*,a.display_name,a.username FROM bluehaven_blog_posts p JOIN bluehaven_authors a ON a.id=p.author_id ORDER BY CASE p.status WHEN \\'pending\\' THEN 0 WHEN \\'draft\\' THEN 1 ELSE 2 END,p.updated_at DESC');return send(res,{posts:x.rows.map(shape)})}if(params.get('mine')==='1'){if(!a)return send(res,{error:'Unauthorized'},401);const x=await q.query('SELECT p.*,a.display_name,a.username FROM bluehaven_blog_posts p JOIN bluehaven_authors a ON a.id=p.author_id WHERE p.author_id=$1 ORDER BY p.updated_at DESC',[a.id]);return send(res,{posts:x.rows.map(shape)})}const x=await q.query('SELECT p.*,a.display_name,a.username FROM bluehaven_blog_posts p JOIN bluehaven_authors a ON a.id=p.author_id WHERE p.status=\\'published\\' ORDER BY p.published_at DESC NULLS LAST,p.created_at DESC');return send(res,{posts:x.rows.map(shape)})}
if(req.method!=='POST')return send(res,{error:'Method not allowed'},405);const d=body(req),action=String(d.action||''),admin=isAdmin(req),a=await me(q,req);
if(action==='register'){const name=String(d.displayName||'').trim().slice(0,120),username=String(d.username||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,40),email=String(d.email||'').trim().toLowerCase().slice(0,254),password=String(d.password||'');if(name.length<2||username.length<3||!/^\S+@\S+\.\S+$/.test(email)||password.length<12||password.length>128)return send(res,{error:'Use a name, valid email, username (3+ characters) and password (12–128 characters).'},400);if((await q.query('SELECT id FROM bluehaven_authors WHERE email=$1 OR username=$2 LIMIT 1',[email,username])).rows[0])return send(res,{error:'That email or username is already in use.'},409);const id=randomUUID();await q.query('INSERT INTO bluehaven_authors(id,display_name,username,email,password_hash) VALUES($1,$2,$3,$4,$5)',[id,name,username,email,await makeHash(password)]);const t=randomBytes(32).toString('base64url');await q.query('INSERT INTO bluehaven_writer_sessions(id,author_id,token_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL \\'30 days\\')',[randomUUID(),id,hash(t)]);return send(res,{ok:true,author:{id,display_name:name,username,email}},200,{'set-cookie':COOKIE+'='+t+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000'})}
if(action==='login'){const identity=String(d.identity||'').trim().toLowerCase(),password=String(d.password||'');const x=await q.query('SELECT id,display_name,username,email,password_hash FROM bluehaven_authors WHERE email=$1 OR username=$1 LIMIT 1',[identity]);if(!x.rows[0]||!(await checkHash(password,x.rows[0].password_hash)))return send(res,{error:'Invalid email/username or password.'},401);const t=randomBytes(32).toString('base64url');await q.query('DELETE FROM bluehaven_writer_sessions WHERE author_id=$1',[x.rows[0].id]);await q.query('INSERT INTO bluehaven_writer_sessions(id,author_id,token_hash,expires_at) VALUES($1,$2,$3,NOW()+INTERVAL \\'30 days\\')',[randomUUID(),x.rows[0].id,hash(t)]);return send(res,{ok:true,author:{id:x.rows[0].id,display_name:x.rows[0].display_name,username:x.rows[0].username,email:x.rows[0].email}},200,{'set-cookie':COOKIE+'='+t+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000'})}
if(action==='logout'){const t=cookie(req);if(t)await q.query('DELETE FROM bluehaven_writer_sessions WHERE token_hash=$1',[hash(t)]);return send(res,{ok:true},200,{'set-cookie':COOKIE+'=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
if(['publish','reject','admin_delete'].includes(action)){if(!admin)return send(res,{error:'Admin authorization required'},403);const id=String(d.id);if(action==='admin_delete')await q.query('DELETE FROM bluehaven_blog_posts WHERE id=$1',[id]);else await q.query('UPDATE bluehaven_blog_posts SET status=$1,published_at=CASE WHEN $1=\\'published\\' THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=$2',[action==='publish'?'published':'rejected',id]);return send(res,{ok:true})}
if(!a)return send(res,{error:'Please sign in to write.'},401);if(action==='delete'){await q.query('DELETE FROM bluehaven_blog_posts WHERE id=$1 AND author_id=$2',[String(d.id),a.id]);return send(res,{ok:true})}if(!['create','update','submit'].includes(action))return send(res,{error:'Unknown action'},400);
const title=String(d.title||'').trim().slice(0,180),excerpt=String(d.excerpt||'').trim().slice(0,500),content=String(d.content||'').trim(),category=String(d.category||'Community').trim().slice(0,80);if(title.length<3||content.length<80)return send(res,{error:'Add a title and at least 80 characters of content.'},400);const c=d.cover_data_url?cover(d.cover_data_url):null;
if(action==='create'){let s=makeSlug(String(d.slug||title)),n=1;while((await q.query('SELECT id FROM bluehaven_blog_posts WHERE slug=$1 LIMIT 1',[s])).rows[0])s=makeSlug(String(d.slug||title))+'-'+n++;const id=randomUUID();await q.query('INSERT INTO bluehaven_blog_posts(id,author_id,title,slug,excerpt,content,category,cover_data,cover_mime,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,a.id,title,s,excerpt,content,category,c?.bytes||null,c?.mime||null,d.submit?'pending':'draft']);return send(res,{ok:true,id,status:d.submit?'pending':'draft'})}
const id=String(d.id),own=(await q.query('SELECT status FROM bluehaven_blog_posts WHERE id=$1 AND author_id=$2 LIMIT 1',[id,a.id])).rows[0];if(!own)return send(res,{error:'Post not found'},404);const status=action==='submit'||own.status==='published'?'pending':own.status;await q.query('UPDATE bluehaven_blog_posts SET title=$1,excerpt=$2,content=$3,category=$4,status=$5,published_at=CASE WHEN $5=\\'published\\' THEN COALESCE(published_at,NOW()) ELSE NULL END,cover_data=CASE WHEN $6::boolean THEN $7 ELSE cover_data END,cover_mime=CASE WHEN $6::boolean THEN $8 ELSE cover_mime END,updated_at=NOW() WHERE id=$9 AND author_id=$10',[title,excerpt,content,category,status,Boolean(c),c?.bytes||null,c?.mime||null,id,a.id]);return send(res,{ok:true,status})
}catch(e){console.error('BlueHaven community blog',e);return send(res,{error:e instanceof Error?e.message:'Blog service error'},500)}}