import { neon } from '@neondatabase/serverless';
import { createHmac, timingSafeEqual } from 'node:crypto';

type Req={method?:string;headers?:Record<string,string|undefined>;body?:unknown}; type Res={status:(n:number)=>Res;setHeader:(n:string,v:string)=>Res;json:(d:unknown)=>void};
const sql=()=>{if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');return neon(process.env.DATABASE_URL)};
const secret=()=>process.env.BLUEHAVEN_ADMIN_PASSWORD||process.env.ADMIN_PASSWORD||'';
const auth=(r:Req)=>{const raw=(r.headers?.cookie||r.headers?.Cookie||'').match(/(?:^|;\s*)bluehaven_admin=([^;]+)/)?.[1];if(!raw||!secret())return false;const p=raw.split('.');if(p.length!==3)return false;const e=Buffer.from(createHmac('sha256',secret()).update(`${p[0]}.${p[1]}`).digest('base64url')),a=Buffer.from(p[2]);return a.length===e.length&&timingSafeEqual(a,e)};
const body=(r:Req)=>{if(r.body&&typeof r.body==='object')return r.body as Record<string,unknown>;if(typeof r.body==='string'){try{return JSON.parse(r.body)}catch{}}return {}};
const send=(res:Res,d:unknown,s=200)=>{res.status(s).setHeader('content-type','application/json').setHeader('cache-control','no-store').json(d)};
export default async function handler(req:Req,res:Res){try{const db=sql();if(req.method==='GET'){const rows=await db`SELECT setting_value FROM site_settings WHERE setting_key='active_buddy' LIMIT 1`;const v=(rows as any[])[0]?.setting_value;return send(res,{active_buddy:v==='skales'?'skales':'bubbles'})}if(req.method!=='POST')return send(res,{error:'Method not allowed'},405);if(!auth(req))return send(res,{error:'Unauthorized'},401);const b=body(req);if(b.action!=='set')return send(res,{error:'Unknown action'},400);const v=b.active_buddy==='skales'?'skales':'bubbles';await db`INSERT INTO site_settings (setting_key,setting_value,updated_at) VALUES ('active_buddy',${JSON.stringify(v)}::jsonb,NOW()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=${JSON.stringify(v)}::jsonb,updated_at=NOW()`;return send(res,{ok:true,active_buddy:v})}catch(e){console.error('BlueHaven buddy API error:',e);return send(res,{error:e instanceof Error?e.message:'Server error'},500)}}
