import { neon } from '@neondatabase/serverless';
import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { safeSlug } from '../src/lib/adminValidation.js';

type Req={method?:string;url?:string;headers?:Record<string,string|undefined>;body?:unknown};
type Res={status:(n:number)=>Res;setHeader:(n:string,v:string)=>Res;json:(d:unknown)=>void;end:(d?:unknown)=>void};
const MAX_UPLOAD_BYTES=12*1024*1024;
const db=()=>{if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL is not configured');return neon(process.env.DATABASE_URL)};
const secret=()=>process.env.BLUEHAVEN_ADMIN_PASSWORD||process.env.ADMIN_PASSWORD||'';
const auth=(r:Req)=>{const raw=(r.headers?.cookie||r.headers?.Cookie||'').match(/(?:^|;\s*)bluehaven_admin=([^;]+)/)?.[1];if(!raw||!secret())return false;const p=raw.split('.');if(p.length!==3)return false;const e=Buffer.from(createHmac('sha256',secret()).update(`${p[0]}.${p[1]}`).digest('base64url')),a=Buffer.from(p[2]);return a.length===e.length&&timingSafeEqual(a,e)};
const body=(r:Req)=>{if(r.body&&typeof r.body==='object')return r.body as Record<string,unknown>;if(typeof r.body==='string'){try{return JSON.parse(r.body)}catch{}}return {}};
const send=(res:Res,d:unknown,s=200)=>{res.status(s).setHeader('content-type','application/json');res.setHeader('cache-control','no-store');res.json(d)};
const params=(r:Req)=>new URL(r.url||'/','https://bluehaven.local').searchParams;
const decode=(v:unknown)=>{const m=String(v||'').match(/^data:([^;]+);base64,(.+)$/s);if(!m)throw new Error('Invalid image data');const bytes=Buffer.from(m[2],'base64');if(bytes.length>MAX_UPLOAD_BYTES)throw new Error('Cover image is larger than 12MB');if(!['image/jpeg','image/png','image/webp'].includes(m[1]))throw new Error('Cover image must be JPG, PNG or WebP');return {mime:m[1],bytes}};
async function ensure(db:any){await db`CREATE TABLE IF NOT EXISTS bluehaven_stories (id UUID PRIMARY KEY,title VARCHAR(180) NOT NULL,slug VARCHAR(220) UNIQUE NOT NULL,excerpt VARCHAR(500) NOT NULL DEFAULT '',content TEXT NOT NULL DEFAULT '',category VARCHAR(80) NOT NULL DEFAULT 'Studio Journal',cover_data BYTEA,cover_mime VARCHAR(80),published BOOLEAN NOT NULL DEFAULT false,featured BOOLEAN NOT NULL DEFAULT false,published_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await db`CREATE INDEX IF NOT EXISTS bluehaven_stories_public_idx ON bluehaven_stories(published,featured,published_at DESC)`)}
function shape(s:any){const copy={...s};delete copy.cover_data;return {...copy,cover_url:s.cover_data?`/api/story-media?id=${s.id}`:null}}
export default async function handler(req:Req,res:Res){try{const database=db();await ensure(database);const q=params(req);
 if(req.method==='GET'){const slug=q.get('slug');if(slug){const rows=await database`SELECT id,title,slug,excerpt,content,category,cover_data,cover_mime,published,featured,published_at,created_at FROM bluehaven_stories WHERE slug=${slug} AND published=true LIMIT 1`;if(!rows[0])return send(res,{error:'Story not found'},404);return send(res,{story:shape(rows[0])})}if(!auth(req)){const rows=await database`SELECT id,title,slug,excerpt,category,cover_data,cover_mime,published,featured,published_at,created_at FROM bluehaven_stories WHERE published=true ORDER BY featured DESC,published_at DESC NULLS LAST,created_at DESC`;return send(res,{stories:rows.map(shape)})}const rows=await database`SELECT id,title,slug,excerpt,content,category,cover_data,cover_mime,published,featured,published_at,created_at,updated_at FROM bluehaven_stories ORDER BY featured DESC,published_at DESC NULLS LAST,created_at DESC`;return send(res,{stories:rows.map(shape)})}
 if(!auth(req))return send(res,{error:'Unauthorized'},401);
 if(req.method!=='POST')return send(res,{error:'Method not allowed'},405);const b=body(req),action=String(b.action||'');
 if(action==='create'||action==='update'){const title=String(b.title||'').trim().slice(0,180),slug=safeSlug(String(b.slug||title)).slice(0,220),excerpt=String(b.excerpt||'').trim().slice(0,500),content=String(b.content||''),category=String(b.category||'Studio Journal').trim().slice(0,80),published=Boolean(b.published),featured=Boolean(b.featured);if(!title||!content)return send(res,{error:'Title and story content are required'},400);const cover= b.cover_data_url ? decode(b.cover_data_url) : null; const coverBytes=cover?.bytes ?? null; const coverMime=cover?.mime ?? null; if(action==='create'){const id=randomUUID();await database`INSERT INTO bluehaven_stories(id,title,slug,excerpt,content,category,cover_data,cover_mime,published,featured,published_at,created_at,updated_at) VALUES(${id},${title},${slug},${excerpt},${content},${category},${coverBytes},${coverMime},${published},${featured},${published?new Date().toISOString():null},NOW(),NOW())`;return send(res,{ok:true,id})}const id=String(b.id);await database`UPDATE bluehaven_stories SET title=${title},slug=${slug},excerpt=${excerpt},content=${content},category=${category},published=${published},featured=${featured},published_at=CASE WHEN ${published} THEN COALESCE(published_at,NOW()) ELSE NULL END,cover_data=CASE WHEN ${coverBytes!==null} THEN ${coverBytes} ELSE cover_data END,cover_mime=CASE WHEN ${coverMime!==null} THEN ${coverMime} ELSE cover_mime END,updated_at=NOW() WHERE id=${id}`;return send(res,{ok:true})}
 if(action==='toggle'){await database`UPDATE bluehaven_stories SET published=NOT published,published_at=CASE WHEN NOT published THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=${String(b.id)}`;return send(res,{ok:true})}
 if(action==='delete'){await database`DELETE FROM bluehaven_stories WHERE id=${String(b.id)}`;return send(res,{ok:true})}
 return send(res,{error:'Unknown action'},400);
 }catch(e){console.error('BlueHaven stories API error:',e);return send(res,{error:e instanceof Error?e.message:'Server error'},500)}}
